import asyncio
import shutil
import time
from pathlib import Path

from langchain_core.documents import Document
from pdf2image import convert_from_path
from pypdf import PdfReader

from multimodal.config import config
from multimodal.services.openai_service import OpenAIService
from multimodal.services.qdrant_service import QdrantService
from multimodal.utils.logger import get_logger

logger = get_logger(__name__)


class IndexingService:
    def __init__(self, qdrant_service: QdrantService, openai_service: OpenAIService) -> None:
        self.qdrant_service = qdrant_service
        self.openai_service = openai_service

        config.uploads_dir.mkdir(parents=True, exist_ok=True)
        config.page_images_dir.mkdir(parents=True, exist_ok=True)

    async def build_index(self) -> dict:
        index_start = time.perf_counter()

        # 1) Read the source PDF from uploads folder.
        pdf_path = self._get_upload_pdf_path()

        # 2) Clear only generated outputs from the previous run.
        self._clear_previous_images()

        # 3) Reset vector collection so every run starts fresh.
        self.qdrant_service.clear_collection()

        # 4) Build one Document per page and push them to Qdrant.
        page_documents, page_token_usage = await self._build_page_documents(pdf_path=pdf_path)
        logger.info("Upserting %d page documents into Qdrant", len(page_documents))
        self.qdrant_service.add_documents(page_documents)
        logger.info("Qdrant upsert complete in %.2fs", time.perf_counter() - index_start)

        return {
            "input_pdf_path": str(pdf_path),
            "indexed_files": 1,
            "indexed_pages": len(page_documents),
            "qdrant_path": str(config.qdrant_path.resolve()),
            "qdrant_collection": config.qdrant_collection_name,
            "pages": page_token_usage,
        }

    def _get_upload_pdf_path(self) -> Path:
        pdf_files = sorted(config.uploads_dir.glob("*.pdf"))
        if not pdf_files:
            raise FileNotFoundError(f"No PDF found in uploads folder: {config.uploads_dir.resolve()}")
        return pdf_files[0]

    def _clear_previous_images(self) -> None:
        # Keep the mounted root folder (e.g. /app/page_images in Docker) and clear only its contents.
        if config.page_images_dir.exists():
            for child in config.page_images_dir.iterdir():
                if child.is_dir():
                    shutil.rmtree(child)
                else:
                    child.unlink()
        config.page_images_dir.mkdir(parents=True, exist_ok=True)

    async def _build_page_documents(self, pdf_path: Path) -> tuple[list[Document], list[dict[str, int]]]:
        # Extract plain text from each page (best-effort).
        reader = PdfReader(str(pdf_path))
        page_texts = [(page.extract_text() or "").strip() for page in reader.pages]

        # Convert all pages to images in a thread to avoid blocking event loop.
        page_images = await asyncio.to_thread(convert_from_path, str(pdf_path), dpi=160, fmt="jpeg")

        pdf_image_dir = config.page_images_dir / pdf_path.stem
        pdf_image_dir.mkdir(parents=True, exist_ok=True)

        # Save all page images concurrently before starting model calls.
        image_paths = [pdf_image_dir / f"page_{i + 1}.jpg" for i in range(len(page_images))]
        await asyncio.gather(
            *(
                asyncio.to_thread(image.save, str(image_path), "JPEG")
                for image, image_path in zip(page_images, image_paths, strict=False)
            )
        )

        page_documents: list[Document] = []
        page_token_usage: list[dict[str, int]] = []
        for index, image_path in enumerate(image_paths):
            page_start = time.perf_counter()
            page_number = index + 1

            description, token_usage = await self.openai_service.describe_pdf_page(
                image_path=image_path,
                page_number=page_number,
            )
            extracted_text = page_texts[index] if index < len(page_texts) else ""

            # Retrieval content is only the multimodal page description generated by the vision model.
            # Raw extracted text is kept in metadata for inspection/debug use.
            page_content = description.strip() or "(empty page description)"
            page_elapsed = time.perf_counter() - page_start
            logger.info(
                "\n\nPage %d indexed in %.2fs | input_tokens=%d output_tokens=%d total_tokens=%d\nDescription:\n%s\n\n",
                page_number,
                page_elapsed,
                token_usage["input_tokens"],
                token_usage["output_tokens"],
                token_usage["total_tokens"],
                page_content,
            )
            page_token_usage.append(
                {
                    "page_number": page_number,
                    "input_tokens": token_usage["input_tokens"],
                    "output_tokens": token_usage["output_tokens"],
                    "total_tokens": token_usage["total_tokens"],
                }
            )

            page_documents.append(
                Document(
                    page_content=page_content,
                    metadata={
                        "source": pdf_path.name,
                        "page_number": page_number,
                        "image_path": str(image_path),
                        "extracted_text": extracted_text,
                        "input_tokens": token_usage["input_tokens"],
                        "output_tokens": token_usage["output_tokens"],
                        "total_tokens": token_usage["total_tokens"],
                    },
                )
            )

        return page_documents, page_token_usage
